# NTU-Pred H5数据集 Point-BERT预训练配置
# 针对已增强的H5文件的预训练配置

optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0002,
    weight_decay: 0.05,
    betas: [0.9, 0.999]
  }
}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 50,
    initial_epochs: 10,
    warming_up_init_lr: 0.00002
  }
}

# 温度退火配置
temp: {
  start: 1.0,
  target: 0.2,
  ntime: 110000
}

# KL散度权重配置
kldweight: {
  start: 0.0,
  target: 0.01,
  ntime: 110000
}

# 数据集配置
dataset: {
  train: { 
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml, 
    others: {
      subset: 'train', 
      npoints: 720,  # 使用完整的720个增强点
      augment: true,
      whole: false
    }
  },
  val: { 
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml, 
    others: {
      subset: 'val', 
      npoints: 720,  # 使用完整的720个增强点
      augment: false,
      whole: false
    }
  },
  test: { 
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml, 
    others: {
      subset: 'test', 
      npoints: 720,  # 使用完整的720个增强点
      augment: false,
      whole: false
    }
  }
}

# Point-BERT模型配置  
model:
  NAME: MaskedSkeletonTokenizer
  group_size: 32
  num_group: 18
  encoder_dims: 384

# 训练设置
total_bs: 64
step_per_update: 1
max_epoch: 50
use_gpu: true
val_freq: 10
num_workers: 4
seed: 2021

# 预训练任务配置
pretrain_task: {
  type: 'masked_point_modeling',
  mask_ratio: 0.6,
  loss_type: 'cdl1'  # Chamfer Distance L1
}

# H5数据集特定设置
h5_config: {
  data_key: 'enhanced_data',      # H5文件中的数据键
  coordinate_conversion: true,     # 是否需要坐标转换
  frame_selection: 'middle',       # 帧选择策略：middle/random/all
  validation_checks: true,         # 启用数据验证检查
}

# 预训练阶段标识
stage: "point_bert_pretrain_h5"
task: "masked_point_modeling"
experiment_name: "ntu_pred_h5_point_bert_pretrain"
description: "基于NTU-Pred H5增强数据的Point-BERT预训练"

# 数据路径设置
data_paths: {
  h5_data_root: './data/NTU-Pred',
  original_skeleton_root: './data/NTU-RGB+D',
  output_root: './experiments/ntu_pred_h5_point_bert_pretrain'
}

# 性能优化配置
performance: {
  prefetch_factor: 2,
  pin_memory: true,
  persistent_workers: true,
}

# 日志配置
logging: {
  log_level: 'INFO',
  save_visualization: true,
  vis_interval: 50,
  checkpoint_interval: 10
}

# 验证指标配置
consider_metric: 'CDL1'  # 主要评估指标
