# NTU RGB+D 优化多区域DGCNN DVAE预训练配置
# 使用OptimizedMaskedSkeletonTokenizer解决跨区域KNN干扰问题
# 50轮训练配置

optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0005,  # 适当提高学习率，新架构需要更多学习
    weight_decay: 0.0005  # 减少正则化，避免过度约束
  }
}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 50,   # 50轮训练
    initial_epochs: 5,   # 预热轮数
    warming_up_init_lr: 0.00005  # 预热学习率
  }
}

# 早停配置 - 50轮训练
early_stopping: {
  patience: 10,      # 10轮无改善则停止
  min_delta: 0.001,  # 最小改善阈值
  monitor: 'CDL1'    # 监控CDL1指标
}

# dVAE相关参数 - 50轮调度
temp: {
  start: 1.0,
  target: 0.2,      # 提高最终温度，避免过于硬化
  ntime: 110000     # 调度时间 (50轮 * 2217批次)
}

kldweight: {
  start: 0.0,
  target: 0.01,     # 降低KL权重，避免损失爆炸
  ntime: 110000     # 调度时间
}

# 数据集配置 - 使用7分组策略
dataset: {
  train: { 
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml, 
    others: {
      subset: 'train',
      npoints: 720,           # 720点架构
      anatomical_groups: 7,   # 7分组架构
      augment: true,
      whole: false
    }
  },
  val: { 
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml, 
    others: {
      subset: 'val',
      npoints: 720,
      anatomical_groups: 7,
      augment: false,
      whole: false
    }
  },
  test: {
    _base_: cfgs/dataset_configs/NTU_Pred_H5.yaml,
    others: {
      subset: 'test',
      npoints: 720,
      anatomical_groups: 7,
      augment: false,
      whole: false
    }
  }
}

# 优化多区域DGCNN架构配置
model: {
  NAME: MaskedSkeletonTokenizer,  # 使用正确的模型名称
  
  # 解剖学分组配置
  num_anatomical_groups: 7,  # 7个解剖学分组
  anatomical_group_sizes: [25, 63, 27, 135, 135, 163, 172],  # 各组点数
  
  # 编码器配置
  encoder_dims: 384,         # 编码器维度
  
  # 优化多区域DGCNN配置
  multi_region_dgcnn: {
    num_regions: 6,          # 6个处理区域 (跳过初始25个关节点)
    region_processors: {
      head_neck: {
        type: "MLP",         # 2个中心点使用MLP
        num_centers: 2,
        max_distance: 0.3
      },
      torso: {
        type: "Graph",       # 3个中心点使用Graph
        num_centers: 3,
        max_distance: 0.5
      },
      left_arm: {
        type: "Graph",       # 6个中心点使用Graph
        num_centers: 6,
        max_distance: 0.8
      },
      right_arm: {
        type: "Graph",       # 6个中心点使用Graph
        num_centers: 6,
        max_distance: 0.8
      },
      left_leg: {
        type: "Graph",       # 4个中心点使用Graph
        num_centers: 4,
        max_distance: 1.0
      },
      right_leg: {
        type: "Graph",       # 4个中心点使用Graph
        num_centers: 4,
        max_distance: 1.0
      }
    },
    knn_k: 3,               # KNN邻居数
    graph_conv_layers: 3,    # 图卷积层数
    feature_dims: [128, 256, 512],  # 图卷积特征维度
    output_dim: 512         # 输出特征维度
  },
  
  # 改进码本配置
  codebook: {
    size: 512,              # 码本大小
    tokens_dims: 256,       # 码字维度
    num_groups: 6,          # 6个区域各自编码
    temperature_scheduling: true
  },
  
  # 解码器配置
  decoder_dims: 384,        # 解码器维度
  
  # 解剖学约束
  anatomical_constraints: {
    enforce_distance_limits: true,    # 强制距离限制
    prevent_cross_region_knn: true,   # 防止跨区域KNN
    center_point_source: "initial_joints"  # 中心点来源
  }
}

# 训练设置
total_bs: 32                # 批次大小
step_per_update: 1          # 梯度累积
max_epoch: 50               # 50轮训练
use_gpu: true
val_freq: 5                 # 每5轮验证一次
num_workers: 4              # 工作进程数
seed: 2021
consider_metric: CDL1

# 实验信息
stage: "optimized_multi_region_pretrain"
task: "skeleton_reconstruction"
experiment_name: "ntu_optimized_multi_region_dgcnn_50epochs"
description: "NTU RGB+D优化多区域DGCNN预训练，解决跨区域KNN干扰，50轮训练"

# 架构创新信息
optimization_info: {
  innovation: "cross_region_knn_interference_solution",
  key_features: [
    "6_independent_region_processors",
    "anatomical_distance_constraints", 
    "adaptive_graph_mlp_selection",
    "25_anatomical_center_points_utilization"
  ],
  solved_problems: [
    "waist_points_misclassified_as_hand_points",
    "25_vs_6_logical_contradiction",
    "cross_region_spatial_interference",
    "unreasonable_anatomical_connections"
  ],
  expected_improvements: [
    "better_anatomical_structure_preservation",
    "improved_spatial_locality",
    "reduced_reconstruction_artifacts",
    "enhanced_skeleton_coherence"
  ]
}

# 数据流信息
data_flow_info: {
  input: "(B, 720, 3)",
  processing_layers: [
    "AnatomicalGroupDivider", 
    "AnatomicalEncoder",
    "OptimizedMultiRegionDGCNN",
    "ImprovedCodebook", 
    "SecondOptimizedMultiRegionDGCNN",
    "AnatomicalDecoder"
  ],
  output: "6_reconstructed_groups + (B, 6, 512) logits"
}
